name: Render video Manual
on:
  workflow_dispatch:
jobs:
  lanuchServ:
    name: node
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: npm i
      - name: create env file
        run: |
          touch .env
          echo CRYPTOCURRENCY_API_KEY=${{ secrets.CRYPTOCURRENCY_API_KEY }} >> .env
      - run: node getPriceFromAPIweb.js
  render:
    name: Render video
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run build
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}

      - uses: actions/upload-artifact@v2
        with:
          name: video.mp4
          path: out/video.mp4
